# Generated by Django 4.2.5 on 2023-09-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_financial_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EODData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('adjusted_close', models.FloatField()),
                ('volume', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='FinancialModel',
        ),
    ]
